//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comm2
    {
        public string No_Com { get; set; }
        public Nullable<short> Ligneitm { get; set; }
        public Nullable<short> Ligneopt { get; set; }
        public string Famille { get; set; }
        public string Item { get; set; }
        public string Des { get; set; }
        public string Des2 { get; set; }
        public string Des3 { get; set; }
        public string Des4 { get; set; }
        public Nullable<decimal> Qte_Com { get; set; }
        public Nullable<decimal> Qte_Exp { get; set; }
        public Nullable<decimal> Qte_Fac { get; set; }
        public Nullable<decimal> Qte_Bo { get; set; }
        public string Complet { get; set; }
        public string Code_Gl { get; set; }
        public Nullable<decimal> Prixbase { get; set; }
        public Nullable<decimal> Escompte { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public Nullable<decimal> Remise { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string Taxes_Cod { get; set; }
        public string Devise { get; set; }
        public string Job { get; set; }
        public string Export { get; set; }
        public Nullable<System.DateTime> Dateliv { get; set; }
        public Nullable<System.DateTime> Datepro { get; set; }
        public string No_Rev { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Qte_Pro { get; set; }
        public string Typejob { get; set; }
        public string No_Lot { get; set; }
        public string Division { get; set; }
        public Nullable<decimal> Psetup { get; set; }
        public string Psetupi { get; set; }
        public int Clef { get; set; }
        public string Reserve { get; set; }
        public string Location { get; set; }
        public Nullable<int> Clef_Parent { get; set; }
        public string Code_Ope { get; set; }
        public string Listeparents { get; set; }
        public string Codecli { get; set; }
        public string Unite { get; set; }
        public string Provenanceprix { get; set; }
        public Nullable<double> Conversiondos_Clef { get; set; }
        public byte[] Stimestamp { get; set; }
        public string Lot_Inv { get; set; }
        public Nullable<decimal> PrixCore { get; set; }
        public byte Statut { get; set; }
        public Nullable<System.DateTime> DateClient { get; set; }
        public Nullable<byte> Niveau { get; set; }
        public Nullable<int> Bom_Code_Id { get; set; }
        public bool OptionManuelle { get; set; }
        public int FacteurMultiplicatif { get; set; }
        public bool ContientOptions { get; set; }
        public Nullable<int> Clef_ItemMaitre { get; set; }
        public decimal Qte_Pick { get; set; }
        public string COD_CustomerOrderHeaderLink { get; set; }
        public string COD_ItemLink { get; set; }
        public string COD_JobLink { get; set; }
        public string COD_UnitLink { get; set; }
        public string COD_InventoryBatchLink { get; set; }
        public string COD_GLAccountLink { get; set; }
        public System.DateTime COD_CreateDate { get; set; }
        public Nullable<System.DateTime> COD_LastUpdate { get; set; }
        public string COD_LastUser { get; set; }
        public Nullable<decimal> COD_NetQuantityOrdered { get; set; }
        public Nullable<short> JobPlanningStrategy { get; set; }
        public Nullable<System.DateTime> DateJobProductionStart { get; set; }
        public string COD_FullSearch { get; set; }
        public int PricingMode { get; set; }
        public Nullable<int> NonConformityId { get; set; }
        public int DistributionMode { get; set; }
        public decimal Dev_Fact { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<int> EstimateDocumentID { get; set; }
    
        public virtual Comm Comm { get; set; }
    }
}
