//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_Master_Sales_Orders_hist
    {
        public long MSO_Key { get; set; }
        public string Project_Tracker_Number { get; set; }
        public string Sales_Order_Number { get; set; }
        public string Username { get; set; }
        public long Date_Entered { get; set; }
        public long Time_Entered { get; set; }
    }
}
