//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_Master
    {
        public string Project_Tracker_Number { get; set; }
        public string Project_Name { get; set; }
        public long Start_Date { get; set; }
        public long End_Date { get; set; }
        public string Notes { get; set; }
        public string Open_Or_Closed { get; set; }
        public string Emergency_Hold_Status { get; set; }
        public string Emergency_Hold_Notes { get; set; }
    }
}
