//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_Project_SalesOrder_Part
    {
        public string Project_Key { get; set; }
        public string Sales_Order_Key { get; set; }
        public short Sales_Order_Line_Number { get; set; }
        public short Department_Key { get; set; }
        public string Part { get; set; }
        public long Start_Date { get; set; }
        public long End_Date { get; set; }
        public string Notes { get; set; }
        public string Completed_Yes_No { get; set; }
        public decimal Plan_Hrs { get; set; }
        public decimal Actual_Hrs { get; set; }
    }
}
