//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_Project_Line_Department
    {
        public string Project_Tracker_Number { get; set; }
        public short Sales_Order_Line_Number { get; set; }
        public int Department_Key { get; set; }
        public string User_Responsible { get; set; }
    }
}
