//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PT_User_Department
    {
        public string PT_User { get; set; }
        public int Department_Key { get; set; }
        public string Head_Yes_No { get; set; }
    }
}
