//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ice_Project_TrackerEntities : DbContext
    {
        public Ice_Project_TrackerEntities()
            : base("name=Ice_Project_TrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PT_Department> PT_Department { get; set; }
        public virtual DbSet<PT_Master> PT_Master { get; set; }
        public virtual DbSet<PT_Master_hist> PT_Master_hist { get; set; }
        public virtual DbSet<PT_Master_Sales_Orders> PT_Master_Sales_Orders { get; set; }
        public virtual DbSet<PT_Master_Sales_Orders_hist> PT_Master_Sales_Orders_hist { get; set; }
        public virtual DbSet<PT_Project_Department> PT_Project_Department { get; set; }
        public virtual DbSet<PT_Project_Line_Department> PT_Project_Line_Department { get; set; }
        public virtual DbSet<PT_Project_SalesOrder_Part> PT_Project_SalesOrder_Part { get; set; }
        public virtual DbSet<PT_Project_SalesOrder_Part_hist> PT_Project_SalesOrder_Part_hist { get; set; }
        public virtual DbSet<PT_User> PT_User { get; set; }
        public virtual DbSet<PT_User_Department> PT_User_Department { get; set; }
    }
}
