//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comm()
        {
            this.Comm2 = new HashSet<Comm2>();
        }
    
        public string No_Com { get; set; }
        public string No_Po { get; set; }
        public string Soumission { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Fact_A1 { get; set; }
        public string Fact_A2 { get; set; }
        public string Fact_A3 { get; set; }
        public string Fact_A4 { get; set; }
        public string Fact_A5 { get; set; }
        public string Exp_A1 { get; set; }
        public string Exp_A2 { get; set; }
        public string Exp_A3 { get; set; }
        public string Exp_A4 { get; set; }
        public string Exp_A5 { get; set; }
        public string Compte { get; set; }
        public string Exp_Mod { get; set; }
        public string Exp_Tra { get; set; }
        public string Exp_Fab { get; set; }
        public string Contact { get; set; }
        public string Term { get; set; }
        public string Vendeur { get; set; }
        public string Territoire { get; set; }
        public string Devise { get; set; }
        public decimal Dev_Fact { get; set; }
        public string Taxes_Dflt { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string No_Usager { get; set; }
        public string Note_Entet { get; set; }
        public string Imprime { get; set; }
        public Nullable<System.DateTime> Dateliv { get; set; }
        public Nullable<double> Clef { get; set; }
        public Nullable<System.DateTime> Datecli { get; set; }
        public string Exp_A6 { get; set; }
        public Nullable<double> Esc_Reel { get; set; }
        public string No_Rev { get; set; }
        public string Explose { get; set; }
        public string Revente { get; set; }
        public Nullable<System.DateTime> Daterev { get; set; }
        public string Psetupi { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Dateref { get; set; }
        public string Refsup1 { get; set; }
        public string Refsup2 { get; set; }
        public string Faxcontact { get; set; }
        public string Telcontact { get; set; }
        public string Fact_A6 { get; set; }
        public string Interloc { get; set; }
        public string Route { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Poidscom { get; set; }
        public string Statut { get; set; }
        public bool RMA { get; set; }
        public string COH_BillToCustomerLink { get; set; }
        public string COH_Link { get; set; }
        public string COH_ShipToCustomerLink { get; set; }
        public string COH_CarrierLink { get; set; }
        public string COH_PaymentTermLink { get; set; }
        public string COH_SalesmanLink { get; set; }
        public string COH_TerritoryLink { get; set; }
        public string COH_CurrencyLink { get; set; }
        public string COH_TaxGroupLink { get; set; }
        public string COH_WarehouseLink { get; set; }
        public string COH_RoadLink { get; set; }
        public int COH_Id { get; set; }
        public Nullable<System.DateTime> COH_LastUpdate { get; set; }
        public string COH_LastUser { get; set; }
        public bool COH_Active { get; set; }
        public string COH_ShipToCountryCode { get; set; }
        public string COH_BillToAddress2 { get; set; }
        public string COH_BillToProvinceCode { get; set; }
        public string COH_BillToCountryCode { get; set; }
        public string COH_ShipToAddress2 { get; set; }
        public string COH_ShipToProvinceCode { get; set; }
        public string COH_ShipToCountryLink { get; set; }
        public string COH_BillToProvinceLink { get; set; }
        public string COH_BillToCountryLink { get; set; }
        public string COH_ShipToProvinceLink { get; set; }
        public Nullable<int> COH_StatusSystemLink { get; set; }
        public Nullable<int> COH_StatusUserLink { get; set; }
        public byte[] Stimestamp { get; set; }
        public string COH_ShippingModeLink { get; set; }
        public Nullable<System.DateTime> DateJobProductionStart { get; set; }
        public string COH_FullSearch { get; set; }
        public Nullable<int> RefLotSerialId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public bool IsManualRevisionDate { get; set; }
        public Nullable<int> AdvancedBillingDistributionMode { get; set; }
        public int TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comm2> Comm2 { get; set; }
    }
}
